### ISSUE TITLE
Write a program to Use ADC1, ADC2 and ADC3 in Triple interleaved mode and DMA mode2

### ISSUE THREAD

**Issue by bhavindarji** [Edutech-ARM/STM32F4-Dev#142]

**Comment by kelu124** [comment]
Out of curiosity, did you manage to do this?

**Comment by bhavindarji** [comment]
I did use the triple interleaved mode and dma mode but not with the 6msps...
Actually I forgot to remove that...sorry

**Comment by kelu124** [comment]
No issue! Even out of curiosity, could you point to the code you used for the triple interleaved mode? Thanks in advance!

**Comment by bhavindarji** [comment]
Sure... 
Driver: STM32F4-Dev -> Project_templates -> stm32f4_bsp_template ->Drivers -> BSP-> stm32f4_discovery_adc.c
Example : STM32F4-Dev -> Example Projects -> ADC -> Eg6 -> Src ->main.c
